# Generated by Django 5.2.17 on 2026-10-03 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('preference', 'Preference'), ('workflow', 'Workflow'), ('project', 'Project'), ('security_policy', 'Security Policy'), ('fact', 'Fact')], default='preference', max_length=30)),
                ('source', models.CharField(choices=[('explicit', 'Explicit'), ('chat', 'Chat')], default='explicit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='assistant_a_user_id_33e4d7_idx'), models.Index(fields=['user', 'category'], name='assistant_a_user_id_b0353b_idx')],
            },
        ),
    ]
