# Generated by Django 5.2.17 on 2026-10-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=1024)),
                ('quarantine_filename', models.CharField(max_length=255)),
                ('quarantine_path', models.CharField(max_length=1024)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('verdict', models.CharField(default='quarantined', max_length=64)),
                ('status', models.CharField(choices=[('quarantined', 'Quarantined'), ('restored', 'Restored'), ('deleted', 'Deleted')], default='quarantined', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='security_qu_user_id_eb8314_idx'), models.Index(fields=['sha256'], name='security_qu_sha256_377ec0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Original or inspected path of the file', max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('md5', models.CharField(blank=True, default='', max_length=32)),
                ('entropy', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('likely_malicious', 'Likely Malicious')], default='clean', max_length=32)),
                ('threat_score', models.IntegerField(default=0, help_text='Score from 0 (clean) to 100 (high risk)')),
                ('evidence', models.JSONField(blank=True, default=list, help_text='List of fact/inference/confidence items')),
                ('file_metadata', models.JSONField(blank=True, default=dict, help_text='PE sections, hashes, archive stats')),
                ('is_quarantined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='security_sc_user_id_627c83_idx'), models.Index(fields=['sha256'], name='security_sc_sha256_934a1b_idx')],
            },
        ),
    ]
