# Generated by Django 5.2.17 on 2026-10-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('tool_name', models.CharField(max_length=100)),
                ('risk_level', models.SmallIntegerField(blank=True, null=True)),
                ('decision', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
