# Generated by Django 5.2.17 on 2026-10-02 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('client_ip', models.CharField(blank=True, default='', max_length=50)),
                ('query_type', models.CharField(default='A', max_length=20)),
                ('response', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(default='lookup', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('vendor', models.CharField(blank=True, default='Unknown Vendor', max_length=255)),
                ('label', models.CharField(choices=[('mine', 'Mine'), ('family', 'Family'), ('guest', 'Guest'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'mac_address')},
            },
        ),
        migrations.CreateModel(
            name='NetworkAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('new_device', 'New Device Discovered'), ('ip_changed', 'IP Address Changed'), ('device_offline', 'Device Offline')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='info', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='network.networkdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='network.networkdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSubnetConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=50)),
                ('gateway_ip', models.CharField(blank=True, default='', max_length=50)),
                ('interface_name', models.CharField(blank=True, default='', max_length=100)),
                ('confirmed_by_user', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_subnets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at'],
                'unique_together': {('user', 'subnet')},
            },
        ),
    ]
